version: '3.8'
services:
  redis-node-1:
    image: redis:7.0
    container_name: redis-node-1
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./data/node-1:/data
      - ./data/node-1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2
    depends_on: []

  redis-node-2:
    image: redis:7.0
    container_name: redis-node-2
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./data/node-2:/data
      - ./data/node-2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-node-3:
    image: redis:7.0
    container_name: redis-node-3
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./data/node-3:/data
      - ./data/node-3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-node-4:
    image: redis:7.0
    container_name: redis-node-4
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./data/node-4:/data
      - ./data/node-4/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5

  redis-node-5:
    image: redis:7.0
    container_name: redis-node-5
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./data/node-5:/data
      - ./data/node-5/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

  redis-node-6:
    image: redis:7.0
    container_name: redis-node-6
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - ./data/node-6:/data
      - ./data/node-6/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.7

  redis-node-7:
    image: redis:7.0
    container_name: redis-node-7
    ports:
      - "7007:7007"
      - "17007:17007"
    volumes:
      - ./data/node-7:/data
      - ./data/node-7/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.8

  redis-node-8:
    image: redis:7.0
    container_name: redis-node-8
    ports:
      - "7008:7008"
      - "17008:17008"
    volumes:
      - ./data/node-8:/data
      - ./data/node-8/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.9

  redis-node-9:
    image: redis:7.0
    container_name: redis-node-9
    ports:
      - "7009:7009"
      - "17009:17009"
    volumes:
      - ./data/node-9:/data
      - ./data/node-9/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.10

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
